# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.10.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.10.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/milicakostic/CLionProjects/RG013-speedracing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/milicakostic/CLionProjects/RG013-speedracing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.10.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.10.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/milicakostic/CLionProjects/RG013-speedracing/CMakeFiles /Users/milicakostic/CLionProjects/RG013-speedracing/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/milicakostic/CLionProjects/RG013-speedracing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SpeedRacing

# Build rule for target.
SpeedRacing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SpeedRacing
.PHONY : SpeedRacing

# fast build rule for target.
SpeedRacing/fast:
	$(MAKE) -f CMakeFiles/SpeedRacing.dir/build.make CMakeFiles/SpeedRacing.dir/build
.PHONY : SpeedRacing/fast

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/SpeedRacing.dir/build.make CMakeFiles/SpeedRacing.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/SpeedRacing.dir/build.make CMakeFiles/SpeedRacing.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/SpeedRacing.dir/build.make CMakeFiles/SpeedRacing.dir/main.c.s
.PHONY : main.c.s

model.o: model.c.o

.PHONY : model.o

# target to build an object file
model.c.o:
	$(MAKE) -f CMakeFiles/SpeedRacing.dir/build.make CMakeFiles/SpeedRacing.dir/model.c.o
.PHONY : model.c.o

model.i: model.c.i

.PHONY : model.i

# target to preprocess a source file
model.c.i:
	$(MAKE) -f CMakeFiles/SpeedRacing.dir/build.make CMakeFiles/SpeedRacing.dir/model.c.i
.PHONY : model.c.i

model.s: model.c.s

.PHONY : model.s

# target to generate assembly for a file
model.c.s:
	$(MAKE) -f CMakeFiles/SpeedRacing.dir/build.make CMakeFiles/SpeedRacing.dir/model.c.s
.PHONY : model.c.s

texture.o: texture.c.o

.PHONY : texture.o

# target to build an object file
texture.c.o:
	$(MAKE) -f CMakeFiles/SpeedRacing.dir/build.make CMakeFiles/SpeedRacing.dir/texture.c.o
.PHONY : texture.c.o

texture.i: texture.c.i

.PHONY : texture.i

# target to preprocess a source file
texture.c.i:
	$(MAKE) -f CMakeFiles/SpeedRacing.dir/build.make CMakeFiles/SpeedRacing.dir/texture.c.i
.PHONY : texture.c.i

texture.s: texture.c.s

.PHONY : texture.s

# target to generate assembly for a file
texture.c.s:
	$(MAKE) -f CMakeFiles/SpeedRacing.dir/build.make CMakeFiles/SpeedRacing.dir/texture.c.s
.PHONY : texture.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... SpeedRacing"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... model.o"
	@echo "... model.i"
	@echo "... model.s"
	@echo "... texture.o"
	@echo "... texture.i"
	@echo "... texture.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

